url: ""
baseurl: ""
destination: "localserver"
theme: chulapa-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
pure_relative_paths: true